with Gbada.Types; use Gbada.Types;
with Gbada.Memory; use Gbada.Memory;

package Gbada.CPU.Instructions is

  -- Read the next byte at PC
  procedure Read_Instruction;

  function Instruction_String return String;

private

  type Instruction is
    record
      Image : String (1..14);
      Operands : UInt16;
      M_Cycles : UInt8;
    end record;

  type Instr_Arr is array (UInt8'Range) of Instruction;
  Instr_Info : constant Instr_Arr := (
    -- 0x00 --
    ("NOP           ", 1, 1),
    ("LD BC, d16    ", 2, 3),
    ("LD (BC), A    ", 1, 2),
    ("INC BC        ", 1, 2),
    ("INC B         ", 1, 1),
    ("DEC B         ", 1, 1),
    ("LD B, d8      ", 2, 2),
    ("RLCA          ", 1, 1),
    ("LD (a16), SP  ", 3, 5),
    ("ADD HL, BC    ", 1, 2),
    ("LD A, (BC)    ", 1, 2),
    ("DEC BC        ", 1, 2),
    ("INC C         ", 1, 1),
    ("DEC C         ", 1, 1),
    ("LD C, d8      ", 2, 2),
    ("RRCA          ", 1, 1),
    -- 0x10 --
    ("STOP d8       ", 2, 1),
    ("LD DE, d16    ", 3, 3),
    ("LD (DE), A    ", 1, 2),
    ("INC DE        ", 1, 2),
    ("INC D         ", 1, 1),
    ("DEC D         ", 1, 1),
    ("LD D, d8      ", 2, 2),
    ("RLA           ", 1, 1),
    ("JR r8         ", 2, 3),
    ("ADD HL, DE    ", 1, 2),
    ("LD A, (DE)    ", 1, 2),
    ("DEC DE        ", 1, 2),
    ("INC E         ", 1, 1),
    ("DEC E         ", 1, 1),
    ("LD E, d8      ", 2, 2),
    ("RRA           ", 1, 1),
    -- 0x20 --
    ("JR NZ, r8     ", 2, 3),
    ("LD HL, d16    ", 3, 3),
    ("LDI (HL), A   ", 1, 2),
    ("INC HL        ", 1, 2),
    ("INC H         ", 1, 1),
    ("DEC H         ", 1, 1),
    ("LD H, d8      ", 2, 2),
    ("DAA           ", 1, 1),
    ("JR Z, r8      ", 2, 3),
    ("ADD HL, HL    ", 1, 2),
    ("LDI A, (HL)   ", 1, 2),
    ("DEC HL        ", 1, 2),
    ("INC L         ", 1, 1),
    ("DEC L         ", 1, 1),
    ("LD L, d8      ", 2, 2),
    ("CPL           ", 1, 1),
    -- 0x30 --
    ("JR NC, r8     ", 2, 3),
    ("LD SP, d16    ", 3, 3),
    ("LDD (HL), A   ", 1, 2),
    ("INC SP        ", 1, 2),
    ("INC (HL)      ", 1, 3),
    ("DEC (HL)      ", 1, 3),
    ("LD (HL), d8   ", 2, 3),
    ("SCF           ", 1, 1),
    ("JR C, r8      ", 2, 3),
    ("ADD HL, SP    ", 1, 2),
    ("LDD A, (HL)   ", 1, 2),
    ("DEC SP        ", 1, 2),
    ("INC A         ", 1, 1),
    ("DEC A         ", 1, 1),
    ("LD A, d8      ", 2, 2),
    ("CCF           ", 1, 1),
    -- 0x40 --
    ("LD B, B       ", 1, 1),
    ("LD B, C       ", 1, 1),
    ("LD B, D       ", 1, 1),
    ("LD B, E       ", 1, 1),
    ("LD B, H       ", 1, 1),
    ("LD B, L       ", 1, 1),
    ("LD B, (HL)    ", 1, 2),
    ("LD B, A       ", 1, 1),
    ("LD C, B       ", 1, 1),
    ("LD C, C       ", 1, 1),
    ("LD C, D       ", 1, 1),
    ("LD C, E       ", 1, 1),
    ("LD C, H       ", 1, 1),
    ("LD C, L       ", 1, 1),
    ("LD C, (HL)    ", 1, 2),
    ("LD C, A       ", 1, 1),
    -- 0x50 --
    ("LD D, B       ", 1, 1),
    ("LD D, C       ", 1, 1),
    ("LD D, D       ", 1, 1),
    ("LD D, E       ", 1, 1),
    ("LD D, H       ", 1, 1),
    ("LD D, L       ", 1, 1),
    ("LD D, (HL)    ", 1, 2),
    ("LD D, A       ", 1, 1),
    ("LD E, B       ", 1, 1),
    ("LD E, C       ", 1, 1),
    ("LD E, D       ", 1, 1),
    ("LD E, E       ", 1, 1),
    ("LD E, H       ", 1, 1),
    ("LD E, L       ", 1, 1),
    ("LD E, (HL)    ", 1, 2),
    ("LD E, A       ", 1, 1),
    -- 0x60 --
    ("LD H, B       ", 1, 1),
    ("LD H, C       ", 1, 1),
    ("LD H, D       ", 1, 1),
    ("LD H, E       ", 1, 1),
    ("LD H, H       ", 1, 1),
    ("LD H, L       ", 1, 1),
    ("LD H, (HL)    ", 1, 2),
    ("LD H, A       ", 1, 1),
    ("LD L, B       ", 1, 1),
    ("LD L, C       ", 1, 1),
    ("LD L, D       ", 1, 1),
    ("LD L, E       ", 1, 1),
    ("LD L, H       ", 1, 1),
    ("LD L, L       ", 1, 1),
    ("LD L, (HL)    ", 1, 2),
    ("LD L, A       ", 1, 1),
    -- 0x70 --
    ("LD (HL), B    ", 1, 2),
    ("LD (HL), C    ", 1, 2),
    ("LD (HL), D    ", 1, 2),
    ("LD (HL), E    ", 1, 2),
    ("LD (HL), H    ", 1, 2),
    ("LD (HL), L    ", 1, 2),
    ("HALT          ", 1, 1),
    ("LD (HL), A    ", 1, 2),
    ("LD A, B       ", 1, 1),
    ("LD A, C       ", 1, 1),
    ("LD A, D       ", 1, 1),
    ("LD A, E       ", 1, 1),
    ("LD A, H       ", 1, 1),
    ("LD A, L       ", 1, 1),
    ("LD A, (HL)    ", 1, 2),
    ("LD A, A       ", 1, 1),
    -- 0x80 --
    ("ADD A, B      ", 1, 1),
    ("ADD A, C      ", 1, 1),
    ("ADD A, D      ", 1, 1),
    ("ADD A, E      ", 1, 1),
    ("ADD A, H      ", 1, 1),
    ("ADD A, L      ", 1, 1),
    ("ADD A, (HL)   ", 1, 2),
    ("ADD A, A      ", 1, 1),
    ("ADC A, B      ", 1, 1),
    ("ADC A, C      ", 1, 1),
    ("ADC A, D      ", 1, 1),
    ("ADC A, E      ", 1, 1),
    ("ADC A, H      ", 1, 1),
    ("ADC A, L      ", 1, 1),
    ("ADC A, (HL)   ", 1, 2),
    ("ADC A, A      ", 1, 1),
    -- 0x90 --
    ("SUB A, B      ", 1, 1),
    ("SUB A, C      ", 1, 1),
    ("SUB A, D      ", 1, 1),
    ("SUB A, E      ", 1, 1),
    ("SUB A, H      ", 1, 1),
    ("SUB A, L      ", 1, 1),
    ("SUB A, (HL)   ", 1, 2),
    ("SUB A, A      ", 1, 1),
    ("SBC A, B      ", 1, 1),
    ("SBC A, C      ", 1, 1),
    ("SBC A, D      ", 1, 1),
    ("SBC A, E      ", 1, 1),
    ("SBC A, H      ", 1, 1),
    ("SBC A, L      ", 1, 1),
    ("SBC A, (HL)   ", 1, 2),
    ("SBC A, A      ", 1, 1),
    -- 0xA0 --
    ("AND A, B      ", 1, 1),
    ("AND A, C      ", 1, 1),
    ("AND A, D      ", 1, 1),
    ("AND A, E      ", 1, 1),
    ("AND A, H      ", 1, 1),
    ("AND A, L      ", 1, 1),
    ("AND A, (HL)   ", 1, 2),
    ("AND A, A      ", 1, 1),
    ("XOR A, B      ", 1, 1),
    ("XOR A, C      ", 1, 1),
    ("XOR A, D      ", 1, 1),
    ("XOR A, E      ", 1, 1),
    ("XOR A, H      ", 1, 1),
    ("XOR A, L      ", 1, 1),
    ("XOR A, (HL)   ", 1, 2),
    ("XOR A, A      ", 1, 1),
    -- 0xB0 --
    ("OR A, B       ", 1, 1),
    ("OR A, C       ", 1, 1),
    ("OR A, D       ", 1, 1),
    ("OR A, E       ", 1, 1),
    ("OR A, H       ", 1, 1),
    ("OR A, L       ", 1, 1),
    ("OR A, (HL)    ", 1, 2),
    ("OR A, A       ", 1, 1),
    ("CP A, B       ", 1, 1),
    ("CP A, C       ", 1, 1),
    ("CP A, D       ", 1, 1),
    ("CP A, E       ", 1, 1),
    ("CP A, H       ", 1, 1),
    ("CP A, L       ", 1, 1),
    ("CP A, (HL)    ", 1, 2),
    ("CP A, A       ", 1, 1),
    -- 0xC0 --
    ("RET NZ        ", 1, 5),
    ("POP BC        ", 1, 3),
    ("JP NZ, a16    ", 3, 4),
    ("JP a16        ", 3, 4),
    ("CALL NZ, a16  ", 3, 6),
    ("PUSH BC       ", 1, 4),
    ("ADD A, d8     ", 2, 2),
    ("RST 00H       ", 1, 4),
    ("RET Z         ", 1, 5),
    ("RET           ", 1, 4),
    ("JP Z, a16     ", 3, 4),
    ("PREFIX        ", 1, 1),
    ("CALL Z, a16   ", 3, 6),
    ("CALL a16      ", 3, 6),
    ("ADC A, r8     ", 2, 2),
    ("RST 08H       ", 1, 4),
    -- 0xD0
    ("RET NC        ", 1, 5),
    ("POP DE        ", 1, 3),
    ("JP NC, a16    ", 3, 4),
    ("Reserved      ", 1, 1),
    ("CALL NC, a16  ", 3, 6),
    ("PUSH DE       ", 1, 4),
    ("SUB A, d8     ", 2, 2),
    ("RST 10H       ", 1, 4),
    ("RET C         ", 1, 5),
    ("RETI          ", 1, 4),
    ("JP C, a16     ", 3, 4),
    ("Reserved      ", 1, 1),
    ("CALL C, a16   ", 3, 6),
    ("Reserved      ", 1, 1),
    ("SBC A, d8     ", 2, 2),
    ("RST 18H       ", 1, 4),
    -- 0xE0 --
    ("LDH (a8), A   ", 2, 3),
    ("POP HL        ", 1, 3),
    ("LD (C), A     ", 1, 2),
    ("Reserved      ", 1, 1),
    ("Reserved      ", 1, 1),
    ("PUSH HL       ", 1, 4),
    ("AND A, d8     ", 2, 2),
    ("RST 20H       ", 1, 4),
    ("ADD SP, r8    ", 2, 4),
    ("JP HL         ", 1, 1),
    ("LD (a16), A   ", 3, 4),
    ("Reserved      ", 1, 1),
    ("Reserved      ", 1, 1),
    ("Reserved      ", 1, 1),
    ("XOR A, d8     ", 2, 2),
    ("RST 28H       ", 1, 4),
    -- 0xF0 --
    ("LDH A, (a8)   ", 2, 3),
    ("POP AF        ", 1, 3),
    ("LD A, (C)     ", 1, 2),
    ("DI            ", 1, 1),
    ("Reserved      ", 1, 1),
    ("PUSH AF       ", 1, 4),
    ("OR A, d8      ", 2, 2),
    ("RST 30H       ", 1, 4),
    ("LD HL, SP + r8", 2, 3),
    ("LD SP, HL     ", 1, 2),
    ("LD A, (a16)   ", 3, 4),
    ("EI            ", 1, 1),
    ("Reserved      ", 1, 1),
    ("Reserved      ", 1, 1),
    ("CP A, d8      ", 2, 2),
    ("RST 38H       ", 1, 4));

  procedure CheckZero with Inline;

  Invalid_Instruction_Call_Exception : exception;

end Gbada.CPU.Instructions;
